In [52]:
import geopandas as gpd
import pandas as pd
import json
from shapely.geometry import Point
import numpy as np

In [53]:
file_path = "C:/Users/lenovo/Desktop/URFU/DataAnalysis_3sem/DTP_GIBDD/data/sverdlovskaia-oblast.geojson"
with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

features = data['features']
df = pd.json_normalize(features)

Проеобразование координат в тип данных shapely.geometry.Point, проеобразование ячеек без значений в тип даных None, т.к. geopandas отказывается создавать geometry по NoneType значениям

In [54]:
def make_point(coords):
    if coords is None:
        return None
    if isinstance(coords, list) and len(coords) == 2:
        try:
            lon, lat = float(coords[0]), float(coords[1])
            if -180 <= lon <= 180 and -90 <= lat <= 90:
                return Point(lon, lat)
        except (ValueError, TypeError):
            pass
    return None

geometry = df['geometry.coordinates'].apply(make_point)

In [55]:
gdf = gpd.GeoDataFrame(df, crs='epsg:4326', geometry=geometry)
gdf.sample(10)

,type,geometry.type,geometry.coordinates,properties.id,properties.tags,properties.light,properties.point.lat,properties.point.long,properties.nearby,properties.region,...,properties.severity,properties.vehicles,properties.dead_count,properties.participants,properties.injured_count,properties.parent_region,properties.road_conditions,properties.participants_count,properties.participant_categories,geometry
8366,Feature,Point,"[60.751444, 56.893717]",331324,[Дорожно-транспортные происшествия],"В темное время суток, освещение включено",56.893717,60.751444,"[Регулируемый пешеходный переход, Регулируемый...",Березовский,...,Тяжёлый,"[{'year': 2019, 'brand': 'ПАЗ', 'color': 'Зеле...",0,[],6,Свердловская область,"[Сухое, Неправильное применение, плохая видимо...",8,[Все участники],POINT (60.751 56.894)
5808,Feature,Point,"[59.816608, 56.847059]",326548,[Дорожно-транспортные происшествия],"В темное время суток, освещение отсутствует",56.847059,59.816608,[],Первоуральск,...,Тяжёлый,"[{'year': 2004, 'brand': 'SKODA', 'color': 'Ин...",0,[],5,Свердловская область,[Сухое],5,[Все участники],POINT (59.817 56.847)
14776,Feature,Point,"[60.632247, 56.844073]",1067984,[Дорожно-транспортные происшествия],Светлое время суток,56.844073,60.632247,"[Многоквартирные жилые дома, Нерегулируемый пе...",Екатеринбург,...,Тяжёлый,"[{'year': 1995, 'brand': 'HONDA', 'color': 'Бе...",0,[],1,Свердловская область,"[Сухое, Нарушения в размещении наружной рекламы]",1,"[Все участники, Мотоциклисты]",POINT (60.632 56.844)
26857,Feature,Point,"[61.668889, 57.970278]",1078961,[Дорожно-транспортные происшествия],"В темное время суток, освещение отсутствует",57.970278,61.668889,[],Алапаевский р-н,...,Тяжёлый,"[{'year': 2006, 'brand': 'MAZDA', 'color': 'Че...",0,"[{'role': 'Пешеход', 'gender': 'Мужской', 'vio...",1,Свердловская область,[Сухое],2,"[Все участники, Пешеходы]",POINT (61.669 57.97)
27797,Feature,Point,"[60.161937, 59.75766]",1510999,[Дорожно-транспортные происшествия],Светлое время суток,59.757660,60.161937,"[Многоквартирные жилые дома, Внутридворовая те...",Краснотурьинск,...,Тяжёлый,"[{'year': 2014, 'brand': 'Прочие марки мотоцик...",0,[],1,Свердловская область,[Сухое],1,"[Все участники, Мотоциклисты]",POINT (60.162 59.758)
22450,Feature,Point,"[58.34, 56.2478]",1074707,[Дорожно-транспортные происшествия],Светлое время суток,56.247800,58.340000,[],Артинский,...,Тяжёлый,"[{'year': 2008, 'brand': 'FORD', 'color': 'Ины...",0,[],1,Свердловская область,[Сухое],2,[Все участники],POINT (58.34 56.248)
15926,Feature,Point,"[60.520302, 56.87194]",1069141,[Дорожно-транспортные происшествия],Светлое время суток,56.871940,60.520302,"[Многоквартирные жилые дома, Остановка обществ...",Екатеринбург,...,Тяжёлый,"[{'year': 1982, 'brand': 'Прочие марки ТС', 'c...",0,"[{'role': 'Пешеход', 'gender': 'Мужской', 'vio...",1,Свердловская область,[Сухое],2,"[Все участники, Пешеходы, Общ. транспорт]",POINT (60.52 56.872)
24890,Feature,Point,"[60.6366, 57.55248]",1077666,[Дорожно-транспортные происшествия],Светлое время суток,57.552480,60.636600,[],Нижний Тагил,...,Тяжёлый,"[{'year': 2006, 'brand': 'DAEWOO', 'color': 'К...",0,[],1,Свердловская область,[Сухое],3,[Все участники],POINT (60.637 57.552)
21604,Feature,Point,"[61.973737, 56.775098]",1074823,[Дорожно-транспортные происшествия],Светлое время суток,56.775098,61.973737,[],Богданович,...,Тяжёлый,"[{'year': 2012, 'brand': 'ВАЗ', 'color': 'Сини...",0,[],2,Свердловская область,"[Отсутствие, плохая различимость горизонтально...",6,[Все участники],POINT (61.974 56.775)
13960,Feature,Point,"[60.541062, 56.817864]",1067164,[Дорожно-транспортные происшествия],Светлое время суток,56.817864,60.541062,"[Многоквартирные жилые дома, Крупный торговый ...",Екатеринбург,...,Тяжёлый,"[{'year': 2012, 'brand': 'AUDI', 'color': 'Кра...",0,[],1,Свердловская область,"[Сухое, Отсутствие дорожных знаков в необходим...",2,"[Все участники, Мотоциклисты]",POINT (60.541 56.818)

In [56]:
def list_to_nan(x):
    if isinstance(x, list) and len(x) == 0:
        return np.nan
    else:
        return x
    
for col in gdf.columns:
    gdf[col] = gdf[col].apply(list_to_nan)

In [57]:
gdf.sample(5)

,type,geometry.type,geometry.coordinates,properties.id,properties.tags,properties.light,properties.point.lat,properties.point.long,properties.nearby,properties.region,...,properties.severity,properties.vehicles,properties.dead_count,properties.participants,properties.injured_count,properties.parent_region,properties.road_conditions,properties.participants_count,properties.participant_categories,geometry
17139,Feature,Point,"[60.629994, 56.810506]",1070360,[Дорожно-транспортные происшествия],"В темное время суток, освещение включено",56.810506,60.629994,"[Административные здания, Регулируемый пешеход...",Екатеринбург,...,Тяжёлый,"[{'year': 2002, 'brand': 'HYUNDAI', 'color': '...",0,NaN,1,Свердловская область,"[Отсутствие, плохая различимость горизонтально...",3,[Все участники],POINT (60.63 56.811)
19438,Feature,Point,"[60.859966, 56.776338]",1072662,[Дорожно-транспортные происшествия],"В темное время суток, освещение отсутствует",56.776338,60.859966,[Мост],Екатеринбург,...,Легкий,"[{'year': 2017, 'brand': 'SKODA', 'color': 'Зе...",0,NaN,1,Свердловская область,"[Отсутствие, плохая различимость горизонтально...",2,[Все участники],POINT (60.86 56.776)
18045,Feature,Point,"[60.514669, 56.878759]",1071262,[Дорожно-транспортные происшествия],Светлое время суток,56.878759,60.514669,"[Нерегулируемый пешеходный переход, Спортивные...",Екатеринбург,...,Легкий,"[{'year': 2017, 'brand': 'ПАЗ', 'color': 'Зеле...",0,NaN,2,Свердловская область,"[Отсутствие, плохая различимость горизонтально...",4,[Все участники],POINT (60.515 56.879)
28506,Feature,Point,"[64.057631, 57.762135]",1080758,[Дорожно-транспортные происшествия],Светлое время суток,57.762135,64.057631,NaN,Слободо-Туринский район,...,Тяжёлый,"[{'year': 2014, 'brand': 'RENAULT', 'color': '...",0,NaN,1,Свердловская область,[Сухое],2,"[Все участники, Мотоциклисты]",POINT (64.058 57.762)
11673,Feature,Point,"[60.599942, 56.784297]",1064880,[Дорожно-транспортные происшествия],Светлое время суток,56.784297,60.599942,"[Многоквартирные жилые дома, Медицинские (лече...",Екатеринбург,...,Легкий,"[{'year': 2008, 'brand': 'VOLKSWAGEN', 'color'...",0,NaN,2,Свердловская область,"[Недостатки зимнего содержания, Заснеженное]",5,[Все участники],POINT (60.6 56.784)

In [60]:
gdf['properties.datetime'] = pd.to_datetime(gdf['properties.datetime'])

gdf = gdf[['properties.datetime'] + [col for col in gdf.columns if col not in ['geometry.coordinates', 'properties.datetime'] + ['geometry.coordinates']]]

gdf_sorted = gdf.sort_values('properties.datetime')
gdf_sorted

,properties.datetime,type,geometry.type,properties.id,properties.tags,properties.light,properties.point.lat,properties.point.long,properties.nearby,properties.region,...,properties.severity,properties.vehicles,properties.dead_count,properties.participants,properties.injured_count,properties.parent_region,properties.road_conditions,properties.participants_count,properties.participant_categories,geometry
18976,2015-01-01 03:00:00,Feature,Point,1072200,[Дорожно-транспортные происшествия],"В темное время суток, освещение включено",56.896944,60.603333,"[Многоквартирные жилые дома, Крупный торговый ...",Екатеринбург,...,Тяжёлый,"[{'year': 2006, 'brand': 'ВАЗ', 'color': 'Иные...",0,NaN,3,Свердловская область,[Обработанное противогололедными материалами],4,[Все участники],POINT (60.603 56.897)
21236,2015-01-01 09:40:00,Feature,Point,1074220,[Дорожно-транспортные происшествия],Светлое время суток,57.368333,61.423611,"[Многоквартирные жилые дома, Жилые дома индиви...",Режевской,...,С погибшими,"[{'year': 2001, 'brand': 'ВАЗ', 'color': 'Иные...",1,NaN,1,Свердловская область,"[Недостатки зимнего содержания, Со снежным нак...",2,[Все участники],POINT (61.424 57.368)
18955,2015-01-01 09:50:00,Feature,Point,1072179,[Дорожно-транспортные происшествия],Светлое время суток,56.881944,60.613333,"[Многоквартирные жилые дома, Иное образователь...",Екатеринбург,...,Тяжёлый,"[{'year': 2004, 'brand': 'ВАЗ', 'color': 'Иные...",0,NaN,4,Свердловская область,"[Недостатки зимнего содержания, Заснеженное]",4,[Все участники],POINT (60.613 56.882)
4021,2015-01-01 17:00:00,Feature,Point,324476,[Дорожно-транспортные происшествия],"В темное время суток, освещение отсутствует",62.353700,56.490700,"[Нерегулируемый пешеходный переход, Остановка ...",Камышловский р-н,...,Легкий,"[{'year': 2000, 'brand': 'NISSAN', 'color': 'С...",0,"[{'role': 'Пешеход, перед ДТП находившийся в (...",1,Свердловская область,[Сухое],2,"[Все участники, Пешеходы]",POINT (56.491 62.354)
18969,2015-01-01 18:30:00,Feature,Point,1072193,[Дорожно-транспортные происшествия],"В темное время суток, освещение включено",56.836667,60.597500,"[Административные здания, Нерегулируемый пешех...",Екатеринбург,...,Легкий,"[{'year': 2007, 'brand': 'TOYOTA', 'color': 'С...",0,"[{'role': 'Пешеход', 'gender': 'Женский', 'vio...",3,Свердловская область,"[Отсутствие, плохая различимость горизонтально...",4,"[Все участники, Пешеходы]",POINT (60.597 56.837)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9208,2025-06-30 15:00:00,Feature,Point,1511019,[Дорожно-транспортные происшествия],Светлое время суток,56.785037,60.535634,"[Многоквартирные жилые дома, Жилые дома индиви...",Екатеринбург,...,Тяжёлый,"[{'year': 2023, 'brand': 'CHERY', 'color': 'Че...",0,"[{'role': 'Пешеход', 'gender': 'Женский', 'vio...",1,Свердловская область,[Сухое],2,"[Все участники, Пешеходы]",POINT (60.536 56.785)
19862,2025-06-30 18:35:00,Feature,Point,1511029,[Дорожно-транспортные происшествия],Светлое время суток,56.808233,60.609941,"[Административные здания, Регулируемый перекре...",Екатеринбург,...,Тяжёлый,"[{'year': 2017, 'brand': 'ПАЗ', 'color': 'Зеле...",0,NaN,1,Свердловская область,"[Отсутствие, плохая различимость горизонтально...",2,[Все участники],POINT (60.61 56.808)
6677,2025-06-30 18:50:00,Feature,Point,1510848,[Дорожно-транспортные происшествия],Светлое время суток,56.995180,59.542068,[Жилые дома индивидуальной застройки],Первоуральск,...,Тяжёлый,"[{'year': 2020, 'brand': 'ВАЗ', 'color': 'Сини...",0,NaN,2,Свердловская область,"[Отсутствие, плохая различимость горизонтально...",3,"[Все участники, Мотоциклисты]",POINT (59.542 56.995)
8320,2025-06-30 20:30:00,Feature,Point,1510854,[Дорожно-транспортные происшествия],Светлое время суток,56.968131,60.541088,"[Регулируемый пешеходный переход, Производстве...",Верхняя Пышма,...,Тяжёлый,"[{'year': 2023, 'brand': 'BMW', 'color': 'Черн...",0,NaN,1,Свердловская область,"[Сухое, Отсутствие дорожных знаков в необходим...",1,"[Все участники, Мотоциклисты]",POINT (60.541 56.968)
21601,2025-06-30 21:33:00,Feature,Point,1510859,[Дорожно-транспортные происшествия],Светлое время суток,56.642277,57.731867,"[Жилые дома индивидуальной застройки, Нерегули...",Красноуфимский р-н,...,Тяжёлый,"[{'year': 2019, 'brand': 'ВАЗ', 'color': 'Иные...",0,NaN,1,Свердловская область,"[Сухое, Отсутствие освещения, Дефекты покрытия...",1,[Все участники],POINT (57.732 56.642)

In [ ]:
gdf['properties.severity'].value_counts(dropna=False)

properties.severity
Легкий         14762
Тяжёлый        11661
С погибшими     3436
Name: count, dtype: int64